### ISSUE TITLE
Scroll vertical inutile sur la page d'accueil

### ISSUE THREAD

**Issue by toverux** [SwagOverflow/kidoikoiaki#18]
Self-descripting title.
On en avait déjà parlé, pensez-y un de ces quatre ;)

```css
html {
    overflow: hidden;
}
```
